/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PrismaMigrateSchema {
  /**
   * The path to the prisma schema eg. 'prisma/schema.prisma'
   */
  schema?: string;
  /**
   * The name of the migration. If no name is provided, the CLI will prompt you.
   */
  name?: string;
  /**
   * Creates a new migration based on the changes in the schema but does not apply that migration.
   */
  createOnly?: boolean;
  /**
   * Skip triggering seed.
   */
  skipSeed?: boolean;
  /**
   * Skip triggering generators (for example, Prisma Client).
   */
  skipGenerate?: boolean;
}
