/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pushes the state of your Prisma schema file to the database without using migrations.
 */
export interface PrismaPushSchema {
  /**
   * The path to the prisma schema eg. 'prisma/schema.prisma'
   */
  schema?: string;
  /**
   * Skip generation of artifacts such as Prisma Client.
   */
  skipGenerate?: boolean;
  /**
   * Resets the database and then updates the schema - useful if you need to start from scratch due to unexecutable migrations.
   */
  forceReset?: boolean;
  /**
   * Ignore data loss warnings. This option is required if as a result of making the schema changes, data may be lost.
   */
  acceptDataLoss?: boolean;
}
